# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import grpc_files.message_pb2 as message__pb2


class EchoStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.accept = channel.unary_unary(
        '/Echo/accept',
        request_serializer=message__pb2.Request.SerializeToString,
        response_deserializer=message__pb2.Response.FromString,
        )


class EchoServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def accept(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EchoServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'accept': grpc.unary_unary_rpc_method_handler(
          servicer.accept,
          request_deserializer=message__pb2.Request.FromString,
          response_serializer=message__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Echo', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
